In [181]:
import os
import pandas as pd
import geopandas as gpd
import rasterio
import re
import numpy as np
import matplotlib.pyplot as plt

In [182]:
# user-defined paths
base_dir = '../../../../datos-notebooks/3.global-data-cba/'
ground_data_name = 'ground_data_170226_validation.gpkg'

In [183]:
# derived paths
ground_data_path = os.path.join(base_dir, 'MRT-prediction/ground_data', ground_data_name)
mrt_path = os.path.join(base_dir, 'MRT-prediction/MRT_1m-15dif.tif')

#### reading and fixing ground data

In [184]:
gdf = gpd.read_file(ground_data_path)
len(gdf)

C:\Users\guada\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyogrio\raw.py:198: RuntimeWarning:

Non-conformant content for record 1 in column start, 2026-02-17T13:38:25.282-03:00, successfully parsed

26

In [185]:
# correct TG1
# Create corrected TG column based on instrument
gdf["tg_corr"] = np.where(
    gdf["Instrument"] == "T1 - Sper Scientific 800036 ",
    0.628 * gdf["TG"] + 9.732,   # apply correction for old instrument
    gdf["TG"]                   # keep original value for new instrument
)

In [186]:
gdf.head(3)

,start,end,today,operador,Instrument,condition,TA,TG,WIND M/S,_Location_latitude,_Location_longitude,_Location_altitude,_Location_precision,picture 1,picture 1_URL,picture 2,picture 2_URL,context,geometry,tg_corr
0,2026-02-17 13:38:25.282000-03:00,2026-02-17 13:40:22.997000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,28.7,31.6,2.7,-31.370683,-64.248834,418.516928,4.985490,image-13_40_8.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_40_19.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24834 -31.36998),31.6000
1,2026-02-17 13:18:53.548000-03:00,2026-02-17 13:41:19.664000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,29.3,32.6,0.0,-31.370702,-64.248856,436.989990,37.895014,image-13_40_38.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_40_47.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24836 -31.36995),30.2048
2,2026-02-17 13:40:23.037000-03:00,2026-02-17 13:44:25.264000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,30.1,38.7,1.6,-31.370693,-64.248813,419.412069,6.055630,image-13_44_10.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_44_18.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24881 -31.37069),38.7000

correcting wind

In [187]:
# Subtract 0.88 for wind extracted with anemometer 2 (grande)
gdf["WIND M/S corr"] = np.where(gdf["Instrument"] == "T2 - TM-188D TENMARS ", gdf["WIND M/S"] - 0.9, gdf["WIND M/S"])
gdf["WIND M/S corr"] = np.where(gdf["WIND M/S corr"] < 0, 0, gdf["WIND M/S corr"])

In [188]:
# calculate mean of wind values
# Convert 'start' to datetime
gdf["end"] = pd.to_datetime(gdf["start"], errors="coerce")

# Sort by time
gdf = gdf.sort_values("start")

# Set as index
gdf = gdf.set_index("start")

# Compute centered rolling mean over 10 minutes (±5 min)
gdf["wind_mean"] = (
    gdf["WIND M/S corr"]
    .rolling(window="10min", center=True, min_periods=1)
    .mean()
    .round(2)
)

# Reset index if necesitas la columna 'start' de nuevo
gdf = gdf.reset_index()

In [189]:
gdf

,start,end,today,operador,Instrument,condition,TA,TG,WIND M/S,_Location_latitude,...,_Location_precision,picture 1,picture 1_URL,picture 2,picture 2_URL,context,geometry,tg_corr,WIND M/S corr,wind_mean
0,2026-02-17 13:18:53.548000-03:00,2026-02-17 13:18:53.548000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,29.3,32.6,0.0,-31.370702,...,37.895014,image-13_40_38.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_40_47.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24836 -31.36995),30.2048,0.0,0.00
1,2026-02-17 13:38:25.282000-03:00,2026-02-17 13:38:25.282000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,28.7,31.6,2.7,-31.370683,...,4.985490,image-13_40_8.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_40_19.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24834 -31.36998),31.6000,1.8,1.07
2,2026-02-17 13:40:23.037000-03:00,2026-02-17 13:40:23.037000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,30.1,38.7,1.6,-31.370693,...,6.055630,image-13_44_10.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_44_18.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24881 -31.37069),38.7000,0.7,0.80
3,2026-02-17 13:41:19.707000-03:00,2026-02-17 13:41:19.707000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,28.9,42.2,0.7,-31.370663,...,5.133179,image-13_44_34.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_44_45.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.24884 -31.37066),36.2336,0.7,0.68
4,2026-02-17 13:44:25.303000-03:00,2026-02-17 13:44:25.303000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,30.7,34.4,0.9,-31.361940,...,4.745827,image-13_57_51.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_58_2.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.23602 -31.36199),34.4000,0.0,0.40
5,2026-02-17 13:45:54.280000-03:00,2026-02-17 13:45:54.280000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,34.4,38.0,0.2,-31.366038,...,1.963066,image-13_55_19.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_55_31.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24194 -31.36604),33.5960,0.2,0.30
6,2026-02-17 13:55:34.807000-03:00,2026-02-17 13:55:34.807000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,35.0,40.9,0.8,-31.366234,...,2.595014,image-13_57_29.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_57_43.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24211 -31.36623),35.4172,0.8,0.60
7,2026-02-17 13:57:46.678000-03:00,2026-02-17 13:57:46.678000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,36.4,42.7,0.3,-31.366936,...,43.756464,image-14_0_5.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_0_15.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.2424 -31.36694),36.5476,0.3,0.48
8,2026-02-17 13:58:05.712000-03:00,2026-02-17 13:58:05.712000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,30.2,38.6,1.6,-31.361905,...,4.747328,image-13_59_41.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-13_59_48.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.23612 -31.3619),38.6000,0.7,0.48
9,2026-02-17 14:00:37.766000-03:00,2026-02-17 14:00:37.766000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,28.9,33.0,1.0,-31.366773,...,4.737180,image-14_9_33.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_9_39.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.22041 -31.3665),33.0000,0.1,0.37
10,2026-02-17 14:07:42.197000-03:00,2026-02-17 14:07:42.197000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,34.8,39.6,0.8,-31.367330,...,38.964453,image-14_10_39.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_10_51.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24262 -31.36733),34.6008,0.8,1.45
11,2026-02-17 14:09:42.501000-03:00,2026-02-17 14:09:42.501000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,29.2,39.4,3.0,-31.366926,...,4.749399,image-14_13_25.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_13_32.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (-64.22022 -31.36693),39.4000,2.1,0.97
12,2026-02-17 14:13:41.359000-03:00,2026-02-17 14:13:41.359000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,30.4,32.5,0.0,-31.364002,...,4.760717,image-14_20_50.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_20_56.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.22504 -31.36397),32.5000,0.0,0.93
13,2026-02-17 14:15:39.932000-03:00,2026-02-17 14:15:39.932000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,37.2,46.8,0.7,-31.367412,...,2.650193,image-14_18_25.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_18_54.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.2428 -31.36741),39.1224,0.7,0.35
14,2026-02-17 14:20:59.184000-03:00,2026-02-17 14:20:59.184000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,31.5,41.1,1.7,-31.364029,...,4.755978,image-14_21_36.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_21_43.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.22504 -31.36403),41.1000,0.8,0.30
15,2026-02-17 14:23:38.997000-03:00,2026-02-17 14:23:38.997000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,31.9,34.8,0.1,-31.367732,...,2.179502,image-14_27_14.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_27_22.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.2431 -31.36799),31.5864,0.1,0.22
16,2026-02-17 14:23:58.814000-03:00,2026-02-17 14:23:58.814000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,30.3,32.5,0.4,-31.357135,...,4.750487,image-14_33_54.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_34_4.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.24663 -31.35722),32.5000,0.0,0.22
17,2026-02-17 14:27:53.815000-03:00,2026-02-17 14:27:53.815000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,32.3,31.8,0.0,-31.368118,...,3.722558,image-14_32_35.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_32_44.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24188 -31.36819),29.7024,0.0,0.02
18,2026-02-17 14:32:47.590000-03:00,2026-02-17 14:32:47.590000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,31.6,30.0,0.0,-31.368851,...,3.745724,image-14_36_31.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_36_41.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24188 -31.36885),28.5720,0.0,0.00
19,2026-02-17 14:34:44.778000-03:00,2026-02-17 14:34:44.778000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,33.5,43.7,0.6,-31.357262,...,4.733129,image-14_36_15.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_36_21.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.2466 -31.35726),43.7000,0.0,0.00
20,2026-02-17 14:36:43.536000-03:00,2026-02-17 14:36:43.536000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,31.8,29.3,0.0,-31.369117,...,2.824456,image-14_39_41.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_39_50.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24216 -31.36912),28.1324,0.0,0.00
21,2026-02-17 14:38:11.793000-03:00,2026-02-17 14:38:11.793000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,30.6,33.1,0.0,-31.356612,...,4.756109,image-14_44_4.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_44_10.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (-64.24993 -31.35675),33.1000,0.0,0.00
22,2026-02-17 14:39:53.176000-03:00,2026-02-17 14:39:53.176000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,31.9,28.9,0.0,-31.369406,...,2.661620,image-14_42_29.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_42_40.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24218 -31.36941),27.8812,0.0,0.30
23,2026-02-17 14:43:15.140000-03:00,2026-02-17 14:43:15.140000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,31.0,29.6,0.0,-31.370119,...,4.748652,image-14_48_22.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_48_30.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24255 -31.37012),28.3208,0.0,0.50
24,2026-02-17 14:44:46.417000-03:00,2026-02-17 14:44:46.417000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,30.1,39.4,2.4,-31.369698,...,4.733090,image-14_53_59.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_54_6.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24414 -31.3697),39.4000,1.5,0.38
25,2026-02-17 14:48:36.526000-03:00,2026-02-17 14:48:36.526000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,30.9,29.7,0.0,-31.370420,...,4.748652,image-14_50_50.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,image-14_51_1.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,park,POINT (-64.24269 -31.37042),28.3836,0.0,0.75

In [190]:
# Parameters
eps = 0.95
D1 = 0.04   # diameter of globe 1 [m] 
D2 = 0.05  # diameter of globe 2 [m] 

# Select diameter according to instrument
D = np.where(gdf["Instrument"] == "T1 - Sper Scientific 800036 ", D1,D2)

# MRT calculation using row-specific diameter
# wind used 0.1 for all cases because values were introducing errores and the changes are not significant (all under 1 m/s)
gdf["MRT"] = (
    (
        (gdf["tg_corr"] + 273.15)**4
        + (1.1e8 * gdf["wind_mean"]**0.6 / (eps * D**0.4)) * (gdf["tg_corr"] - gdf["TA"]) 
    )**0.25
    - 273.15
)

Probando con MRT

In [191]:
# read raster crs and sample values
with rasterio.open(mrt_path) as src:
    mrt_crs = src.crs
    points_proj = gdf.to_crs(mrt_crs)
    samples = list(src.sample(zip(points_proj.geometry.x, points_proj.geometry.y)))
    points_proj['MRT_predicted'] = [s[0] for s in samples]

points_proj['MRT_predicted'] = points_proj['MRT_predicted'].astype(float) 

# METRICS
obs = points_proj['MRT']
pred = points_proj['MRT_predicted']

points_proj['residual'] = pred - obs

# export gpkg
out_gpkg = os.path.join(base_dir, 'MRT-prediction/MRT_points_2026.gpkg')
points_proj.to_file(out_gpkg, driver="GPKG")

In [192]:
points_proj.head()

,start,end,today,operador,Instrument,condition,TA,TG,WIND M/S,_Location_latitude,...,picture 2,picture 2_URL,context,geometry,tg_corr,WIND M/S corr,wind_mean,MRT,MRT_predicted,residual
0,2026-02-17 13:18:53.548000-03:00,2026-02-17 13:18:53.548000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SHADOW,29.3,32.6,0.0,-31.370702,...,image-13_40_47.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (381282.355 6528723.634),30.2048,0.0,0.00,30.204800,36.787640,6.582840
1,2026-02-17 13:38:25.282000-03:00,2026-02-17 13:38:25.282000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,28.7,31.6,2.7,-31.370683,...,image-13_40_19.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (381284.173 6528720.501),31.6000,1.8,1.07,41.359197,36.812473,-4.546724
2,2026-02-17 13:40:23.037000-03:00,2026-02-17 13:40:23.037000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SUN,30.1,38.7,1.6,-31.370693,...,image-13_44_18.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (381240.071 6528640.976),38.7000,0.7,0.80,60.175756,52.308060,-7.867697
3,2026-02-17 13:41:19.707000-03:00,2026-02-17 13:41:19.707000-03:00,2026-02-16,Macarena,T1 - Sper Scientific 800036,SUN,28.9,42.2,0.7,-31.370663,...,image-13_44_45.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,open parking,POINT (381237.656 6528644.274),36.2336,0.7,0.68,55.056821,52.330524,-2.726296
4,2026-02-17 13:44:25.303000-03:00,2026-02-17 13:44:25.303000-03:00,2026-02-16,Guadalupe,T2 - TM-188D TENMARS,SHADOW,30.7,34.4,0.9,-31.361940,...,image-13_58_2.jpg,https://kf.kobotoolbox.org/api/v2/assets/aF3fL...,residential,POINT (382446.075 6529619.412),34.4000,0.0,0.40,41.212535,31.941757,-9.270778

In [193]:

mae = np.mean(np.abs(obs - pred))
rmse = np.sqrt(np.mean((obs - pred)**2))
bias = np.mean(pred - obs)

print("MAE:", mae)
print("RMSE:", rmse)
print("Bias:", bias)

MAE: 5.976872717680521
RMSE: 7.085088529198634
Bias: 0.04144677591222472

In [194]:
import plotly.express as px
import numpy as np
import pandas as pd

obs = points_proj['MRT']
pred = points_proj['MRT_predicted']

# Compute 1:1 line range
m = min(obs.min(), pred.min())
M = max(obs.max(), pred.max())

# Scatter
fig = px.scatter(
    points_proj,
    x=points_proj['MRT'],
    y=points_proj['MRT_predicted'],
    color="condition",
    hover_data=["TG", "TA","WIND M/S", "Instrument"],
)

# 1:1 line
fig.add_scatter(
    x=[m, M],
    y=[m, M],
    mode="lines",
    name="1:1 line"
)

fig.update_layout(
    xaxis_title="Observed MRT °C",
    yaxis_title="Predicted MRT °C",
    title="points_proj comparison"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [195]:
# Compute 1:1 line range
m = min(obs.min(), pred.min())
M = max(obs.max(), pred.max())

# Scatter
fig = px.scatter(
    points_proj,
    x=obs,
    y=pred,
    color="context",
    hover_data=["TG", "TA","WIND M/S", "condition"],
)

# 1:1 line
fig.add_scatter(
    x=[m, M],
    y=[m, M],
    mode="lines",
    name="1:1 line"
)

fig.update_layout(
    xaxis_title="Observed MRT °C",
    yaxis_title="Predicted MRT °C",
    title="points_proj comparison"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [197]:
residuals = obs - pred  # Compute residuals
# Scatter
fig = px.scatter(
    points_proj,
    x=pred,
    y=residuals,
    color="context",
    hover_data=["TG", "TA","WIND M/S", "condition", "Instrument"],
)

# 1:1 line
fig.add_scatter(
    x=[pred.min(), pred.max()],
    y=[0, 0],
    mode="lines",
    name="Zero residual line"
)

fig.update_layout(
    xaxis_title="Predicted MRT °C",
    yaxis_title="Residuals (Obs - Pred)",
    title="points_proj residuals"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

AJUSTANDO MRT PRED

In [198]:
mrt_path = os.path.join(base_dir, 'MRT-prediction/MRT_1m-21dif-5modis.tif')

In [199]:
# read raster crs and sample values
with rasterio.open(mrt_path) as src:
    mrt_crs = src.crs
    points_proj = gdf.to_crs(mrt_crs)
    samples = list(src.sample(zip(points_proj.geometry.x, points_proj.geometry.y)))
    points_proj['MRT_predicted'] = [s[0] for s in samples]

points_proj['MRT_predicted'] = points_proj['MRT_predicted'].astype(float) 

# METRICS
obs = points_proj['MRT']
pred = points_proj['MRT_predicted']

points_proj['residual'] = pred - obs

In [200]:
mae = np.mean(np.abs(obs - pred))
rmse = np.sqrt(np.mean((obs - pred)**2))
bias = np.mean(pred - obs)

print("MAE:", mae)
print("RMSE:", rmse)
print("Bias:", bias)

MAE: 10.24435438978974
RMSE: 11.58173036195575
Bias: -8.624105069931751

In [201]:
# Compute 1:1 line range
m = min(obs.min(), pred.min())
M = max(obs.max(), pred.max())

# Scatter
fig = px.scatter(
    points_proj,
    x=obs,
    y=pred,
    color="condition",
    hover_data=["TG", "TA","WIND M/S", "Instrument"],
)

# 1:1 line
fig.add_scatter(
    x=[m, M],
    y=[m, M],
    mode="lines",
    name="1:1 line"
)

fig.update_layout(
    xaxis_title="Observed MRT °C",
    yaxis_title="Predicted MRT °C",
    title="points_proj comparison"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [202]:
# Compute 1:1 line range
m = min(obs.min(), pred.min())
M = max(obs.max(), pred.max())

# Scatter
fig = px.scatter(
    points_proj,
    x=obs,
    y=pred,
    color="Instrument",
    hover_data=["TG", "TA","WIND M/S", "condition"],
)

# 1:1 line
fig.add_scatter(
    x=[m, M],
    y=[m, M],
    mode="lines",
    name="1:1 line"
)

fig.update_layout(
    xaxis_title="Observed MRT °C",
    yaxis_title="Predicted MRT °C",
    title="points_proj comparison"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [203]:
# Compute 1:1 line range
m = min(obs.min(), pred.min())
M = max(obs.max(), pred.max())

# Scatter
fig = px.scatter(
    points_proj,
    x=obs,
    y=pred,
    color="context",
    hover_data=["TG", "TA","WIND M/S", "condition"],
)

# 1:1 line
fig.add_scatter(
    x=[m, M],
    y=[m, M],
    mode="lines",
    name="1:1 line"
)

fig.update_layout(
    xaxis_title="Observed MRT °C",
    yaxis_title="Predicted MRT °C",
    title="points_proj comparison"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [204]:
residuals = obs - pred  # Compute residuals
# Scatter
fig = px.scatter(
    points_proj,
    x=pred,
    y=residuals,
    color="context",
    hover_data=["TG", "TA","WIND M/S", "condition", "Instrument"],
)

# 1:1 line
fig.add_scatter(
    x=[pred.min(), pred.max()],
    y=[0, 0],
    mode="lines",
    name="Zero residual line"
)

fig.update_layout(
    xaxis_title="Predicted MRT °C",
    yaxis_title="Residuals (Obs - Pred)",
    title="points_proj residuals"
)

fig.update_yaxes(scaleanchor="x", scaleratio=1)

fig.show()

In [ ]:
# revisar correcion por hora (falta)
# revisar correcion por radiacion en el dia (listo - MODIS)

In [205]:
# de acá podemos entender las limitaciones del modelo: 
# no considera reflexión de objetos cercanos, 
# por lo que en residencial (donde las casas cerca reflejan) la observada fue mayor que la predicha
# caso contrario en parque y estacionamiento abierto, donde no hay objetos cercanos que reflejen, entonces la observada fue menor que la predicha